### ISSUE TITLE
Design stages are stored in github and locally

### ISSUE THREAD

**Issue by stefpiatek** [UCL-ARC/qw#16]
As a quality manager, I want all of the design stages for a traceability matrix to be stored in github for user entry, and then tracked locally in version control

Stages:

- [ ] User need
- [ ] Requirement
- [ ] Design output
- [ ] Verification
- [ ] Validation

Functionality:

- [ ] `qw freeze` command to scrape github for the current data
  - [ ] report number of qw items found in github
  - [ ] allow update with or without version change, or don't save
